#!/bin/sh
### BEGIN INIT INFO
# Provides:          conspectus
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: conspectus initscript
# Description:       This file should be placed in /etc/init.d. 
#                    It override the defaults in /lib/init/init-d-script.
### END INIT INFO

# Author: Daniel Eriksson
#
DESC="A UDP server for querying a definitions database"
SERVICE_NAME=conspectus
DIST_DIR=/opt/conspectus
PID_PATH_NAME=/tmp/conspectus.pid
LOG=$DIST_DIR/logging-sv.properties
CP=$DIST_DIR/conspectus-20160209.jar
MAIN=se.abc.conspectus.server.ServerApplication
DB=$DIST_DIR/conspectus-sv.xml

do_start()
{
        echo "Starting $SERVICE_NAME..."
        if [ ! -f $PID_PATH_NAME ]; then
            nohup /usr/bin/java -Djava.util.logging.config.file=$LOG -classpath $CP $MAIN $DB 2>> /dev/null >> /dev/null &
            echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started."
        else
            echo "$SERVICE_NAME is already running."
        fi
}

do_stop()
{
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping..."
            kill $PID;
            echo "$SERVICE_NAME stopped."
            rm $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running."
        fi
}

case $1 in
    start)
	do_start
    ;;
    stop)
	do_stop
    ;;
    restart)
 	do_stop
        do_start
    ;;
esac 
